# Generated by Django 4.1.7 on 2023-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=75)),
                ('discord_id', models.CharField(max_length=75)),
                ('riot_id', models.CharField(max_length=75)),
                ('battle_net_id', models.CharField(max_length=75)),
                ('steam_id', models.CharField(max_length=75)),
                ('epic_games_id', models.CharField(max_length=75)),
            ],
        ),
    ]
